/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.invariants.language.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class InvariantsLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("hu/bme/mit/gamma/invariants/language/parser/antlr/internal/InternalInvariantsLanguage.tokens");
	}
}
