/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.invariants.language.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractInvariantsLanguageScopeProvider extends DelegatingScopeProvider {
}
