/**
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.invariants.language.formatting2;

import com.google.inject.Inject;
import hu.bme.mit.gamma.invariants.language.services.InvariantsLanguageGrammarAccess;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class InvariantsLanguageFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private InvariantsLanguageGrammarAccess _invariantsLanguageGrammarAccess;
}
