/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.invariants.language.ide;


/**
 * Use this class to register ide components.
 */
public class InvariantsLanguageIdeModule extends AbstractInvariantsLanguageIdeModule {
}
