/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.invariants.language.serializer;

import com.google.inject.Inject;
import hu.bme.mit.gamma.invariants.language.services.InvariantsLanguageGrammarAccess;
import invariants.HelloWorld;
import invariants.InvariantsPackage;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class InvariantsLanguageSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private InvariantsLanguageGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == InvariantsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case InvariantsPackage.HELLO_WORLD:
				sequence_HelloWorld(context, (HelloWorld) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     HelloWorld returns HelloWorld
	 *
	 * Constraint:
	 *     {HelloWorld}
	 */
	protected void sequence_HelloWorld(ISerializationContext context, HelloWorld semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
