/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.invariants.language.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import hu.bme.mit.gamma.invariants.language.ide.contentassist.antlr.internal.InternalInvariantsLanguageParser;
import hu.bme.mit.gamma.invariants.language.services.InvariantsLanguageGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class InvariantsLanguageParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(InvariantsLanguageGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, InvariantsLanguageGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getHelloWorldAccess().getGroup(), "rule__HelloWorld__Group__0");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private InvariantsLanguageGrammarAccess grammarAccess;

	@Override
	protected InternalInvariantsLanguageParser createParser() {
		InternalInvariantsLanguageParser result = new InternalInvariantsLanguageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public InvariantsLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(InvariantsLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
