/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.invariants.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class InvariantsLanguageUiModule extends AbstractInvariantsLanguageUiModule {

	public InvariantsLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
