/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.invariants.language.ui;

import com.google.inject.Injector;
import hu.bme.mit.gamma.invariants.language.ui.internal.LanguageActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class InvariantsLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LanguageActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LanguageActivator activator = LanguageActivator.getInstance();
		return activator != null ? activator.getInjector(LanguageActivator.HU_BME_MIT_GAMMA_INVARIANTS_LANGUAGE_INVARIANTSLANGUAGE) : null;
	}

}
