/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.invariants.language;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class InvariantsLanguageRuntimeModule extends AbstractInvariantsLanguageRuntimeModule {
}
