/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.gamma.invariants.language;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class InvariantsLanguageStandaloneSetup extends InvariantsLanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new InvariantsLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
